#!/usr/bin/env bash
set -euo pipefail

PREFIX="${PREFIX:-/opt/temms}"
CONFIG_DIR="${CONFIG_DIR:-/etc/temms}"
DATA_DIR="${DATA_DIR:-/var/lib/temms}"
LOG_DIR="${LOG_DIR:-/var/log/temms}"
SERVICE_NAME="${SERVICE_NAME:-temms}"
EXTRAS="${TEMMS_EXTRAS:-inference}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
INSTALL_SOURCE="${INSTALL_SOURCE:-.}"
TMP_DIR="$(mktemp -d)"

cleanup_tmp_dir() {
    rm -rf "${TMP_DIR}"
}

new_tmp_file() {
    mktemp "${TMP_DIR}/temms.XXXXXX"
}

trap cleanup_tmp_dir EXIT

generate_api_token() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    else
        "${PYTHON_BIN}" -c 'import secrets; print(secrets.token_hex(32))'
    fi
}

sed_escape() {
    printf '%s' "$1" | sed -e 's/[\/&|]/\\&/g'
}

render_service_unit() {
    local output="$1"
    render_path_template deploy/temms.service "${output}"
}

render_path_template() {
    local template="$1"
    local output="$2"
    local prefix config_dir data_dir log_dir

    prefix="$(sed_escape "${PREFIX}")"
    config_dir="$(sed_escape "${CONFIG_DIR}")"
    data_dir="$(sed_escape "${DATA_DIR}")"
    log_dir="$(sed_escape "${LOG_DIR}")"

    sed \
        -e "s|/opt/temms|${prefix}|g" \
        -e "s|/etc/temms|${config_dir}|g" \
        -e "s|/var/lib/temms|${data_dir}|g" \
        -e "s|/var/log/temms|${log_dir}|g" \
        "${template}" > "${output}"
}

install_rendered_template() {
    local mode="$1"
    local owner="$2"
    local group="$3"
    local template="$4"
    local output="$5"
    local tmp_file

    tmp_file="$(new_tmp_file)"
    render_path_template "${template}" "${tmp_file}"
    install -m "${mode}" -o "${owner}" -g "${group}" "${tmp_file}" "${output}"
}

ensure_api_token() {
    local env_file="$1"
    local token

    if grep -Eq '^[[:space:]]*TEMMS_API_TOKEN=.+$' "${env_file}"; then
        echo "  api token:   existing TEMMS_API_TOKEN in ${env_file}"
        return
    fi

    case "${TEMMS_GENERATE_API_TOKEN:-true}" in
        false|False|FALSE|0|no|No|NO)
            echo "  api token:   not generated (TEMMS_GENERATE_API_TOKEN=${TEMMS_GENERATE_API_TOKEN})"
            return
            ;;
    esac

    token="$(generate_api_token)"
    {
        echo ""
        echo "# Generated by deploy/install.sh on first install. Use as X-TEMMS-Token."
        echo "TEMMS_API_TOKEN=${token}"
    } >> "${env_file}"
    chown root:temms "${env_file}"
    chmod 0640 "${env_file}"
    echo "  api token:   generated in ${env_file}"
}

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root: sudo deploy/install.sh" >&2
    exit 1
fi

echo "Installing TEMMS edge agent..."
echo "  prefix:      ${PREFIX}"
echo "  config dir:  ${CONFIG_DIR}"
echo "  data dir:    ${DATA_DIR}"
echo "  log dir:     ${LOG_DIR}"
echo "  extras:      ${EXTRAS}"

if ! id -u temms >/dev/null 2>&1; then
    useradd --system --home-dir "${DATA_DIR}" --shell /usr/sbin/nologin temms
fi

install -d -m 0755 "${PREFIX}"
install -d -o temms -g temms -m 0750 "${DATA_DIR}/models" "${DATA_DIR}/cache" "${DATA_DIR}/packages" "${DATA_DIR}/benchmarks"
install -d -o temms -g temms -m 0750 "${LOG_DIR}"
install -d -m 0755 "${CONFIG_DIR}"
install -d -o temms -g temms -m 0750 "${CONFIG_DIR}/policies"
install -d -m 0755 "${CONFIG_DIR}/slots"

"${PYTHON_BIN}" -m venv "${PREFIX}/venv"
"${PREFIX}/venv/bin/pip" install --upgrade pip
"${PREFIX}/venv/bin/pip" install "${INSTALL_SOURCE}[${EXTRAS}]"

if [ ! -f "${CONFIG_DIR}/temms.yaml" ]; then
    install_rendered_template 0644 root root deploy/temms.conf "${CONFIG_DIR}/temms.yaml"
fi

if [ ! -f "${CONFIG_DIR}/temms.env" ]; then
    install_rendered_template 0640 root temms deploy/temms.env "${CONFIG_DIR}/temms.env"
fi
ensure_api_token "${CONFIG_DIR}/temms.env"

tmp_service="$(new_tmp_file)"
render_service_unit "${tmp_service}"
install -m 0644 "${tmp_service}" "/etc/systemd/system/${SERVICE_NAME}.service"
systemctl daemon-reload

echo "TEMMS installed successfully."
echo "  service:     /etc/systemd/system/${SERVICE_NAME}.service"
echo ""
echo "Next steps:"
echo "  1. Edit ${CONFIG_DIR}/temms.yaml and ${CONFIG_DIR}/temms.env"
echo "  2. Run diagnostics: ${PREFIX}/venv/bin/temms doctor --config ${CONFIG_DIR}/temms.yaml"
echo "  3. Import a signed package: ${PREFIX}/venv/bin/temms import /path/to/model.temms.tar.zst --config ${CONFIG_DIR}/temms.yaml --require-signature --signing-key-file /path/to/key"
echo "  4. Enable service: systemctl enable ${SERVICE_NAME}"
echo "  5. Start service: systemctl start ${SERVICE_NAME}"
echo ""
echo "Control API token:"
echo "  sudo grep '^TEMMS_API_TOKEN=' ${CONFIG_DIR}/temms.env"
